Update connect-container.yml
Better error handling

diff --git a/src/commands/connect-container.yml b/src/commands/connect-container.yml
--- a/src/commands/connect-container.yml
+++ b/src/commands/connect-container.yml
@@ -43,7 +43,12 @@ steps:
         for run in {1..3}; do
           echo "Tailscale connection attempt #${run}"
           tailscale --socket=/tmp/tailscaled.sock up --authkey ${<< parameters.auth-key >>} --hostname=${HOSTNAME} --accept-routes --timeout=10s
+          if [ "$?" = "0" ]; then
+            exit 0
+          fi
         done
+        echo "Error: could not connect to tailscale"
+        exit 1
   - when:
       condition: << parameters.export-proxies >>
       steps:
